Add task 1
katyachok/node-ex pull request #1
Opened 2022-09-20 12:20 UTC by katyachok

task1

2022-09-21 06:46 UTC, k-krasilnikova requested changes

2022-09-21 06:46 UTC, k-krasilnikova commented on index.js
> +const express = require('express')
Let's replace `require` with `import` es6

2022-09-21 06:46 UTC, k-krasilnikova commented on index.js
> +})
Let's create an additional structure to the project:
```
src/main.js
src/modules
->src/modules/greetings
-->src/modules/greetings/constants/index.js
-->src/modules/greetings/routes/index.js
-->src/modules/greetings/controllers/sayHi.js
```
Both of the routes should be combined by common API prefix "/api/greetings" in main.js.
Routing of the greeting module should describe each route and execute right controller like middleware.
Also, could you please move all the messages/templates to the constants file?

2022-09-21 13:36 UTC, katyachok commented on index.js
> +const express = require('express')
done

2022-10-11 11:23 UTC, k-krasilnikova approved these changes
Please one more change and PR is ready to be merged

2022-10-11 11:23 UTC, k-krasilnikova commented on src/modules/greetings/controllers/sayHi.js
> +	else res.status(200).send(getHelloMessage(name));
Could you please replace if with correct semantic view:
```
if (!name) {
 res.status(400).json(HELLO_MESSAGE_DESCRIPTION);
}
 res.status(200).send(getHelloMessage(name));
```

2022-10-11 11:34 UTC, merged